name: build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "SFDX_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
          echo "SFDX_DISABLE_TELEMETRY=true" >> $GITHUB_ENV

      - name: Install sf CLI and connect to Dev Hub
        run:  npm run org:scratch:init

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create scratch org
        run: npm run org:scratch:create

      - name: Push source
        run: npm run org:scratch:deploy 

      - name: Run Apex tests
        run: npm run test

      - name: Delete scratch org
        if: always()
        run: npm run org:scratch:delete 
